blank_issues_enabled: false
contact_links:
  - name: ‚ùì Questions and Support Request
    url: https://github.com/SocketSomeone/necord/discussions
    about: Please visit our Discussions page for questions and support requests.
