name: NPM auto deprecate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  auto-deprecate:
    name: NPM auto deprecate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node v22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deprecate versions
        run: 'npx @favware/npm-deprecate --name "*dev*" --package "necord"'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
